# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23b7e515eb7ddc99d2443b15e1ac5361c440924dad35c21f64e813cf367043cb49bca2bed947c4f2a8ccb0391600bf0e7580a9f27ee214b1eb32d6b559e1a190

test:
  secret_key_base: d43e1c3ff60e8050162a85a83d8396e3ae34278c426f7d739daef7e4e62383b417096b0a31e015d77a6d3cf1c5a43331281771e468547e37c8b40f948fc63776

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
